app2/urls.py
from django.urls import path
from app2.views import *
app_name='one'
urlpatterns=[
    path('orenge/',orenge,name='orenge'),
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
import app2
from app1.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app2/',include('app2.urls')),
    path('green/',green,name='green'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def green(request):
    return render(request,'green.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def orenge(request):
    return render(request,'orenge.html')

templates/green.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><a href="{% url 'one:orenge' %}">go to orenge page</a></center>
    <center><h1>this is html page of green</h1></center>
</body>
</html>

templates/orenge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><a href="{% url 'green' %}"></a>GO TO PAGE GREEN</center>
    <center><h1>this is html page of orenge</h1></center>
</body>
</html>